### ISSUE TITLE
Support another method to save file

### ISSUE THREAD

**Issue by kimcy929** [android/camera-samples#100]
Currently, Android 10 limited storage access so we need to use the system file picker to choose a folder before saving if users don't want to use private storage of the app (because files will not show in the system gallery). 

Camerax supported the method **imageCapture.takePicture(file, executor,...)** but can you support another method as **imageCapture.takePicture(outputStream, executor,...)**?

Here:
**outputStream = contentResolver.openOutputStream(treeUri) // treeUri from Intent.ACTION_OPEN_DOCUMENT_TREE**

I knew CameraX supported **imageCapture.takePicture(executor, object : ImageCapture.OnImageCapturedListener() {
//Handle save image here
}**
 
But if you can support that method, it will more handy.

Thanks!

**Comment by owahltinez** [comment]
Hi @kimcy929 , I highly encourage you to start a new thread at the [developer forums](g.co/camerax/developers) where you can get in touch directly with the product team and they'll tell you what they think of your idea!
