### ISSUE TITLE
Update the CameraX sample to 1.0.0-alpha06

### ISSUE THREAD

**Issue by rahulraj64** [android/camera-samples#103]
Please consider updating the CameraX sample to alpha06 since the alpha05 has some potential bugs and the new version has some breaking changes. We depend up on this official sample to build apps on top of CameraX. If you are not considering to migrate to alpha06 now, atleast consider pushing it as a separate branch.

**Comment by owahltinez** [comment]
Please see #97

**Comment by owahltinez** [comment]
The sample has been updated to `alpha06`
