### ISSUE TITLE
CameraX zoom

### ISSUE THREAD

**Issue by chill-cow** [android/camera-samples#111]
According to the official video from Android Dev Summit 2019 I tried to implement the Zoom feature in CameraX in java. But CameraInfo and CameraControl objects design were changed and I can't find appropriate methods in these interfaces. CameraInfo.getZoomRation() and CameraControl.setZoomZation ().

How I can implement this feature now?

Corresponding Google presentation video -> https://www.youtube.com/watch?v=49lU1NtYE5g&t=25s

**Comment by owahltinez** [comment]
We use this Github repo to track issues with the sample. Please use StackOverflow (tag `android-camerax`) or the [developer forums](g.co/camerax/developers) for questions related to the library.
