### ISSUE TITLE
Any plan update to 1.0.0-alpha07

### ISSUE THREAD

**Issue by Tougee** [android/camera-samples#119]
Hi, cause the 1.0.0-alpha07 has lots of breaking API changes, is there any plan update the demo to show usage of that?

**Comment by xpenatan** [comment]
Google needs to release a new update along with the samples. The getting started is still using a old version... 
https://codelabs.developers.google.com/codelabs/camerax-getting-started/#5

**Comment by owahltinez** [comment]
Since `alpha08` is now out, we will probably skip `alpha07`. We will likely update the getting started codelab once beta is out.
