### ISSUE TITLE
Black Stripes below / beside the camera

### ISSUE THREAD

**Issue by efinder2** [android/camera-samples#120]
I've installed the "Camera2BasicJava" app on multiple Samsung devices(SM-T395, SM-T585...) and multiple emulators. On all of them the camera preview has a black stripe on them. I also tried it with the kotlin version. Same result.

How to create a preview that fills the whole preview?

**Comment by owahltinez** [comment]
Hello @efinder2, please take a look at [AutoFitSurfaceView](https://github.com/android/camera-samples/blob/master/Common/src/main/java/com/example/android/camera2/common/AutoFitSurfaceView.kt) for an example of how you can perform a center-crop transform instead of letter-box.
