### ISSUE TITLE
FragmentCompat.OnRequestPermissionsResultCallback deprecated

### ISSUE THREAD

**Issue by pratikbutani** [android/camera-samples#122]
[FragmentCompat.OnRequestPermissionsResultCallback](https://github.com/android/camera-samples/blob/master/Camera2VideoJava/Application/src/main/java/com/example/android/camera2video/Camera2VideoFragment.java#L68) is deprecated

**Comment by owahltinez** [comment]
I can't find any samples in this repo currently using that deprecated call, please reopen if I'm mistaken.
