### ISSUE TITLE
Cannot import Camera2Formats using Android Studio

### ISSUE THREAD

**Issue by emilieroberts** [android/camera-samples#126]
Camera2Formats seems to depend on "Common" which is not available when you import it through the Android Studio "New -> Import Sample..." dialog.

Repro:
 - open Android Studio
 - New -> Import Sample... -> Camera2Formats
 - Try to build

Expected:
 - it builds

Observed:
 - "Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :common"

**Comment by owahltinez** [comment]
A temporary workaround is to clone the Github repo instead, so it's not currently a blocker for developers. We will investigate how to fix importing directly from Android Studio.
