### ISSUE TITLE
Preview is stretched in emulator in camerax

### ISSUE THREAD

**Issue by shubh261096** [android/camera-samples#129]
TextureView is stretched in the emulator. If I set the width and height of textureview as a square (500dp x 500dp). In the emulator, the preview is stretched and shown in the rectangle. Attaching a screenshot for the same.

Here is my code of fragment_camera.xml:
```
<TextureView
        android:id="@+id/view_finder"
        android:layout_width="500dp"
        android:layout_height="500dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
```

![device-2019-12-20-123323](https://user-images.githubusercontent.com/35653065/71236233-719b0100-2324-11ea-9f63-fe3f58185cc3.png)

**Comment by owahltinez** [comment]
We use this Github repo to track issues with the sample. Please use StackOverflow (tag android-camerax) or the [developer forums](g.co/camerax/developers) for questions related to the library.
