### ISSUE TITLE
camerax update 

### ISSUE THREAD

**Issue by Reginer** [android/camera-samples#131]
CameraX update to alpha08 , how to use it ?

**Comment by WANZIzZ** [comment]
I don't know - -

**Comment by williamycyh** [comment]
> CameraX update to alpha08 , how to use it ?

I even don not know how to use alpha07...  the sample should update

**Comment by syslogic** [comment]
Have forked it here: [`1.0.0-alpha08`](https://github.com/syslogic/camera-samples/tree/1.0.0-alpha08) - but there's still a lot to fix.

**Comment by Reginer** [comment]
@syslogic  thks

**Comment by syslogic** [comment]
Got it merely working; see PR https://github.com/android/camera-samples/pull/141.

**Comment by MahmoudMabrok** [comment]
if issue solved. could you close issue.
