### ISSUE TITLE
java.lang.illegalArgumentException : navigation destination

### ISSUE THREAD

**Issue by AliAzaz** [android/camera-samples#134]
![image](https://user-images.githubusercontent.com/12116478/71412747-e053c380-2670-11ea-9180-7cf201321631.png)

I'm getting this crash in CameraXBasic. Scenario when this crash occurred:
First take the picture --> route to gallery --> delete it --> now route to gallery again --> **CRASH**

**Comment by AliAzaz** [comment]
Kindly do check this @owahltinez

**Comment by syslogic** [comment]
@AliAzaz you were correct - I finally came to the same conclusion:
https://github.com/android/camera-samples/pull/154#discussion_r370461006
