### ISSUE TITLE
Inconsistency on cameraXBasic on LEGACY hardware camera on using preview.enableTorch(true) along with ImageCapture

### ISSUE THREAD

**Issue by asifk1997** [android/camera-samples#139]
Please follow the following instructions before filing a bug:

1. I am using two phones having Camera Hardware level Legacy one is moto G4 plus and other is Gionee P7 max
1.  So what i wanted to do is click Picture with torch on so i called preview.enableTorch(true) so on Moto G4 plus the torch remains on even after capture and saving is complete but on gionee phone the flash blinks during capture
1. So I was wondering why phones having similar camera hardware level were behaving differently.

**Comment by owahltinez** [comment]
We use this Github repo to track issues with the sample. Please use StackOverflow (tag android-camerax) or the [developer forums](g.co/camerax/developers) for questions related to the library.
