### ISSUE TITLE
Camera Basic project preview becomes very slow after adding Image Analysis

### ISSUE THREAD

**Issue by Jimmy-J** [android/camera-samples#140]
The preview becomes very slow after using Image Analysis, the preview returns to normal after being removed

**Comment by owahltinez** [comment]
Hello @Jimmy-J , please provide the following information so we can better figure out the cause of this issue:

- What sample are you seeing this in?
- Did you modify the sample in any way?
- What device make and model are you using?
- Can you please provide the output from logcat?

**Comment by owahltinez** [comment]
Please see PR #160 which might be relevant to this issue.

**Comment by owahltinez** [comment]
Merged the PR, issue should be fixed now.
