### ISSUE TITLE
androidx.core.util.Preconditions.a AndroidRuntime: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by williamycyh** [android/camera-samples#142]
01-06 15:53:32.330 14620 14645 E AndroidRuntime: Process: com.svr.camera.backgroundvideorecorder, PID: 14620
01-06 15:53:32.330 14620 14645 E AndroidRuntime: java.lang.IllegalStateException
01-06 15:53:32.330 14620 14645 E AndroidRuntime:        at androidx.core.util.Preconditions.a(SourceFile:4)
01-06 15:53:32.330 14620 14645 E AndroidRuntime:        at androidx.camera.camera2.impl.Camera.openCaptureSession(SourceFile:2)
01-06 15:53:32.330 14620 14645 E AndroidRuntime:        at androidx.camera.camera2.impl.Camera.onUseCaseReset(SourceFile:10)
01-06 15:53:32.330 14620 14645 E AndroidRuntime:        at androidx.camera.camera2.impl.Camera$11.run(SourceFile:1)
01-06 15:53:32.330 14620 14645 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:761)
01-06 15:53:32.330 14620 14645 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:98)
01-06 15:53:32.330 14620 14645 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:156)
01-06 15:53:32.330 14620 14645 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:61)

I got the crash on my app with Camerax when start record video.... pls help

**Comment by owahltinez** [comment]
We use this Github repo to track issues with the sample. Please use StackOverflow (tag android-camerax) or the [developer forums](g.co/camerax/developers) for questions related to the library.
