### ISSUE TITLE
Update the sample to CameraX alpha08

### ISSUE THREAD

**Issue by rahulraj64** [android/camera-samples#146]
Please consider updating the CameraX sample to alpha08 since it has a lot of breaking changes and the current sample is really outdated.

**Comment by owahltinez** [comment]
Closing as duplicate of #131 

Thanks for bringing this up. We are working on it. Please see PR #141.

**Comment by syslogic** [comment]
@rahulraj64 Please check the PR now (it had an issue, which is now fixed).
