### ISSUE TITLE
Pinch Zooming Function

### ISSUE THREAD

**Issue by movie3105** [android/camera-samples#152]
Hello there i'm a very beginner with android,
can someone tell me how to use pinch zoom in android studio ? i'll ready try use the code in https://stackoverflow.com/questions/32711975/zoom-camera2-preview-using-textureview?noredirect=1&lq=1 but the zoom function still didnt work,

Thanks.

**Comment by owahltinez** [comment]
This repo is for issues related to the samples. Please use StackOverflow for questions related to the API usage or, if it's CameraX-related, join the [developer forums](g.co/camerax/developers)
