### ISSUE TITLE
Black screen if you try to open the app with the front Camera

### ISSUE THREAD

**Issue by aletorresveiga** [android/camera-samples#156]
When trying to open the sample code starting with the front camera in a Samsung Galaxy Tab 2 the preview shows a black screen. The next time you open the front camera preview it shows as expected

**Comment by owahltinez** [comment]
* What sample are you seeing this in?
* Are you making any modifications to the sample code?
* Does anything suspicious appear in the logs?

**Comment by aletorresveiga** [comment]
Sorry, I find out about the problem. If you don't set the same lens facing in the preview and the analyzer the preview shows a black screen. I was changing only the lens facing in the preview.
