### ISSUE TITLE
How to resize image before saving it into file?

### ISSUE THREAD

**Issue by MahmoudMabrok** [android/camera-samples#157]

**Comment by Ezugworie** [comment]
Yes please I need this too, how do I resize the image to 600kb, 2MB is quite a large size

**Comment by MahmoudMabrok** [comment]
@Ezugworie  i meant resize for **dimensions**, if you want resize for **lower size** use `compressor` libraray.

**Comment by owahltinez** [comment]
This repo is used to keep track of issues with the sample. For issues with the CameraX library or questions about how to use it, please use the tag `android-camerax` on StackOverflow, file an issue under the camera component in our [issue tracker](https://issuetracker.google.com/) or join the [developer forums](g.co/camerax/developers).
