### ISSUE TITLE
Turning a device fast enough from one landscape mode into another skips rotation of the camerapreview

### ISSUE THREAD

**Issue by pjahnmodum** [android/camera-samples#165]
Tested on an Xiaomi Mi9T pro on newest Firmware. On an Emulator I could not reproduce this
edit: Tested on Huawei P30Pro too, same Result

**Comment by STFBEE** [comment]
same on Pixel4

**Comment by owahltinez** [comment]
A few questions to help us find out the root cause of this issue:
* What sample are you seeing this in?
* Did you modify the sample in any way?

**Comment by pjahnmodum** [comment]
Hi, thanks for getting back

I was using the CameraXSample (most recent code) and no modifications were made on the code.

**Comment by selvarajmca18** [comment]
Same on Samsung Tab A

**Comment by pjahnmodum** [comment]
Issue been fixed on newsest sample for beta 01

**Comment by owahltinez** [comment]
Great to hear! Thanks for verifying and closing, @pjahnmodum
