### ISSUE TITLE
Video recording with front camera in tablet(portrait mode) shows wrong aspect ratio. 

### ISSUE THREAD

**Issue by PrekshyaBasnet** [android/camera-samples#168]
Devices tested
Emulator: Pixel C API 29
Device: Galaxy Tab S2
Mode: Portrait

I tested the sample app for Kotlin version. And tried recording the video using `val cameraId = manager.cameraIdList[1] ` but the video aspect ratio doesn't seem to work properly.

<img width="469" alt="Screen Shot 2020-02-11 at 3 16 23 pm" src="https://user-images.githubusercontent.com/17633541/74210930-c97d3500-4ce1-11ea-9777-36724611de31.png">

**Comment by owahltinez** [comment]
A few questions to help us find out the root cause of this issue:
* What sample are you seeing this in?
* Did you modify the sample in any way?

**Comment by PrekshyaBasnet** [comment]
What sample are you seeing this in?
- It is in camera sample for Camera2VideoKotlin App.

Did you modify the sample in any way?
- I changed val cameraId = manager.cameraIdList[0] to val cameraId = manager.cameraIdList[1] for front camera.
