### ISSUE TITLE
Stable/beta version

### ISSUE THREAD

**Issue by neuhoffm** [android/camera-samples#176]
Any updates on when the camerax library will be released to beta or even stable?

**Comment by SzasznikaJanos** [comment]
beta version is out :
https://developer.android.com/jetpack/androidx/releases/camera

**Comment by neuhoffm** [comment]
Not sure how I missed that ☹️ any news on a stable release?

**Comment by owahltinez** [comment]
No dates for stable release currently, please stay tuned and join [g.co/camerax/developers](http://g.co/camerax/developers) for more details and future updates.
