### ISSUE TITLE
Using FragmentContainerView in main_activity.xml

### ISSUE THREAD

**Issue by syslogic** [android/camera-samples#178]
[`androidx.fragment.app.FragmentContainerView`](https://developer.android.com/reference/kotlin/androidx/fragment/app/FragmentContainerView) seems to replace `FrameLayout` as the fragment host:

> `FragmentContainerView` is a customized Layout designed specifically for Fragments. It extends `FrameLayout`, so it can reliably handle Fragment Transactions, and it also has additional features to coordinate with fragment behavior.

**Comment by owahltinez** [comment]
This makes sense, although I am a bit wary of adding dependencies for the sake of following guidance alone. What issues are we seeing that would warrant using `FragmentContainerView`?

**Comment by owahltinez** [comment]
It looks like this produces a lint error, so it would make sense to move to `FragmentContainerView` considering how important that appears to be to Android Studio.

**Comment by owahltinez** [comment]
CameraX is already using FragmentContainerView!
