### ISSUE TITLE
How to record a video using front camera with no 180 rotate?

### ISSUE THREAD

**Issue by mny459** [android/camera-samples#184]
As title, I try with Camera2 Api.
If there is some advide, there will be great helpful

**Comment by owahltinez** [comment]
You can either rotate every frame as it is fed to MediaEncoder, provide a hint to MediaEncoder to add metadata to the video (which is not always respected by video players) or transcode the video after it is recorded.

Either way, this repo is for issues with the samples and not for API usage. Feel free to open a StackOverflow question and add the link here for future reference to others.
