### ISSUE TITLE
implementing real-time effects

### ISSUE THREAD

**Issue by msroid** [android/camera-samples#190]
I want to use opencv with android camerax to make real-time effects but I don't know how exactly I should do that!
for example i want to have grayscale preview and for that I use this code:

`val mat = Mat();`
`Utils.bitmapToMat(bitmap, mat);`
`Imgproc.cvtColor(mat, mat, Imgproc.COLOR_RGB2GRAY);`
`Utils.matToBitmap(mat, bitmap);`

but the problem is I don't know how to use ImageAnalysis to get the bitmap and how should I change the preview to show the gray bitmap as the output to user and how to capture image with this new effect!

I appreciate any help.

**Comment by owahltinez** [comment]
Hi @msroid, this repo is for issues with the samples. For questions about usage, please open a question in StackOverflow using the tag `android-camerax` or start a discussion in the [developer forums](https://g.co/camerax/developers).
