### ISSUE TITLE
How to capture photos using different exposure on single shot?

### ISSUE THREAD

**Issue by lalit-gsquad** [android/camera-samples#191]
Hi team,
            I am not posting an issue related to this simple. I need to implement some functionality like photo bracketing. I did lot off research to achieve this, but unable to find out solution. I am using camerax library to capture image. there is a requirement to capture image with multiple exposure values(photo bracketing). I found out some way like new 

> Camera2Config.Extender(configBuilder).setCaptureRequestOption(
>         CaptureRequest.CONTROL_AE_EXPOSURE_COMPENSATION, exposure);

But unable to use this using current version `def camerax_version = "1.0.0-beta01"` also can not any possible alternative to [https://developer.android.com/reference/android/hardware/Camera.Parameters#setExposureCompensation(int)](url) using camerax. Please if you get a chance for this please help me to take out from this. 
Thanks

**Comment by owahltinez** [comment]
Hi @lalit-gsquad, this repo is for issues with the samples. For questions about usage, please open a question in StackOverflow using the tag `android-camerax` or start a discussion in the [developer forums](https://g.co/camerax/developers).
