### ISSUE TITLE
Multicamera Video Capture - Google Pixel 4

### ISSUE THREAD

**Issue by The-TT-Hacker** [android/camera-samples#192]
I have a Google Pixel 4 and I am struggling to create an app which captures 2 videos simultaneously, one from each of the rear facing cameras.

I can easily get video capture from both of the cameras to a preview on the screen using 2 TextureViews but when I use the MediaRecorder class to try and record 2 videos at once the app crashes after a few seconds of recording with no error message to the console.

Has anyone tried doing this before or have any ideas for me to try?

Here is the project extended from the camera2 example for video capture in this repo: https://github.com/The-TT-Hacker/Camera2DualCameraCapture

**Comment by owahltinez** [comment]
Hi @The-TT-Hacker, this repo is for issues with the samples. For questions about usage, please open a question in StackOverflow.

That said, I would expect that unless you are capturing both videos at a fairly low resolution, you are probably hitting the limits of the device ability to encode video -- most devices have a single hardware encoder per format i.e. you can only encode one video at a time with hardware acceleration.

In addition to that, you need to make sure that you are using the [multi-camera APIs](https://medium.com/androiddevelopers/getting-the-most-from-the-new-multi-camera-api-5155fb3d77d9) appropriately, which can be tricky to do.
