### ISSUE TITLE
CameraX : Customise Preview to circular one

### ISSUE THREAD

**Issue by Sowmya-Flickr** [android/camera-samples#193]
I  am trying to implement a Selfie camera app with a Circular Preview for image capture. Please advice on which api is available for this? Working on Camerax Beta version.

**Comment by owahltinez** [comment]
Hi @Sowmya-Flickr, this repo is for issues with the samples and not for questions about the usage of the library. Please post your question in StackOverflow using tag `android-camerax` or send a message to the [developer forums](https://g.co/camerax/developers).
