### ISSUE TITLE
Firebase Face Detection Api issue while using cameraX API

### ISSUE THREAD

**Issue by Anasmirza20** [android/camera-samples#197]
Hi team,

I used Camera X Api for detecting faces in Firebase ML kit because you used the depreciated camera API in our example and I faced a lot of performance issues in it.
CameraX API works perfectly but I am stuck in one place. CameraX uses Texture view in the layout view to open the camera and I want to show 3d objects and filters on the face.
In the firebase example, you use CameraSourcePreview and GraphicOverlay classes in the quickstart sample app to show objects on the relative part of the face but in case of texture view, I can't find any way to show graphic objects on the face.
So, Could you please let me know how to how to achieve the same thing using cameraX API.

Any help will be appreciated.
Thanks

**Comment by owahltinez** [comment]
Hello @Anasmirza20, we will be adding a sample to this repo which uses CameraX + MLKit -- please stay tuned!

**Comment by Anasmirza20** [comment]
Okay, thanks but could you please let me know how much time you will take??

**Comment by owahltinez** [comment]
In the best case scenario I won't be able to have a sample ready for at least another 2-4 weeks. The work was originally planned for early May.

**Comment by Anasmirza20** [comment]
okay, thanks for instant response,
I hope you guys will do this asap.
Keep it up....

**Comment by vitrol4** [comment]
@owahltinez any news?

**Comment by Thivarella** [comment]
@owahltinez do you have any news when it's going to be ready?

**Comment by owahltinez** [comment]
The MLKit repository of samples has now been updated to use the latest version of CameraX: https://github.com/googlesamples/mlkit
