### ISSUE TITLE
Can I use cameraX sample in Ar-Core?

### ISSUE THREAD

**Issue by Anasmirza20** [android/camera-samples#201]
Hi Team,
Hope you are doing well,
I have some doubts, First of all, I am using Ar Core for creating filters and the Ar Core support GlSurfaceView or our own fragment to open the camera but the quality of both is not good as good as the cameraX. So I want to use cameraX for creating filters with ArCore FaceDetection API. Could you please let me know if it is possible to use cameraX with ArCore.
One more question, Can cameraX support beauty filters like change skin color, smoothness, contrast, etc. if yes, So could you please let me know how??
Any help would be appreciated.

**Comment by owahltinez** [comment]
Hi @Anasmirza20 this repository is for issues related to the samples. If you have questions about API usage you can open a question on StackOverflow using the tag `android-camerax` or start a thread in the [developer forums](https://g.co/camerax/developers)
