### ISSUE TITLE
GT-I9508V Focusing can only be successful once

### ISSUE THREAD

**Issue by androidfei** [android/camera-samples#205]
Running the camerax demo focusing on Samsung GT-I9508V can only succeed once

android：5.0.1
device：Samsung GT-I9508V
camerax version：1.0.0-beta02

**Comment by owahltinez** [comment]
Please provide a little more information for us to be able to find the root cause of this issue:
* Did you modify the sample in any way?
* Please provide concrete steps to reproduce this issue

**Comment by jidekrm** [comment]
> Please provide a little more information for us to be able to find the root cause of this issue:
> 
>     * Did you modify the sample in any way?
> 
>     * Please provide concrete steps to reproduce this issue

I observed similar problem. I think the issue has to with the last commit(CameraX beta2 #198 ).
I fixed the issue by undoing changes in that commit.

**Comment by owahltinez** [comment]
CameraX was updated to beta03, please reopen if you still are seeing an issue and provide more concrete information
