### ISSUE TITLE
YuvToRgbConverter sample incorrect working

### ISSUE THREAD

**Issue by AlexanderMatveev** [android/camera-samples#207]
YuvToRgbConverter class generates wrong RGB image.

Creating converter and bitmap:
```kotlin
yuvToRgbConverter = YuvToRgbConverter(applicationContext)
previewBitmap =
            Bitmap.createBitmap(previewSize.width, previewSize.height, Bitmap.Config.RGB_565)
```

Converting ImageProxy image to RGB using example code (https://developer.android.com/training/camerax/analyze):

```kotlin
override fun analyze(imageProxy: ImageProxy, rotationDegrees: Int) {
// ...
yuvToRgbConverter.yuvToRgb(imageProxy.image!!, previewBitmap)
```

Gives result (upper is original TextureView, lower is RGB bitmap result):

![ezgif-6-9e3adcbc01dd](https://user-images.githubusercontent.com/1456669/79670835-77b7c600-81ce-11ea-8041-419460cd0a71.gif)

**Comment by owahltinez** [comment]
Please see [this file](https://github.com/owahltinez/camerax-tflite/blob/master/app/src/main/java/com/android/example/camerax/tflite/CameraActivity.kt) for sample usage. If you are still seeing issues then, unfortunately, it is likely a device bug in the implementation of the YUV to RGB converter and there is not much we can do about it.

**Comment by AlexanderMatveev** [comment]
@owahltinez yes, it's working. Thank you for fast response. I'm closing this issue and going to research example you gave.

**Comment by AlexanderMatveev** [comment]
My mistake was expecting `ImageAnalysis.Analyzer` to return `image` with width and height I'm setting with Preview.Builder's `setTargetResolution` and ImageAnalysis.Builder's `setTargetResolution`. I was creating my bitmap with size not same as Analyzer image.
