### ISSUE TITLE
Reflect changes made to ImageAnalysis.Analyzer in PreviewView

### ISSUE THREAD

**Issue by rruffer** [android/camera-samples#211]
Hello,

I'm using camerax with opencv to scan documents. I implemented an ImageAnalysis.Analyzer for edge detection. Like that:

parahttps: //zaven.co/blog/opencv-advanced-android-development-edge-detection/

I was wondering how I can apply the preview changes made in ImageAnalysis.Analyzer in PreviewView. As if it were an extension effect. This way you would be able to directly view the changes and take photos or record videos with the effects produced.

Currently I have to create an ImageView and update it as if it were the PreviewView. It would be nice if PreviewView already displayed the changes made.

**Comment by owahltinez** [comment]
This repo is for issues with the samples. For questions about usage, please use tag `android-camerax` in StackOverflow or start a thread in the [developer forums](https://g.co/camerax/developers)
