### ISSUE TITLE
CameraX preview issues in camera-view alpha09 & alpha10

### ISSUE THREAD

**Issue by mgarciaguerrero** [android/camera-samples#212]
### Description
I'm facing some issues of your CameraX sample app when running on my testing device. The problem is that the preview is not fully displayed (screenshot below). 

After some investigation, I can confirm it happens in both camera-view versions `alpha09` and `alpha10` (`alpha08` works fine). If I set the `preferredImplementationMode` to use `TextureView` (as recommended in the [documentation](https://developer.android.com/jetpack/androidx/releases/camera#camera-view-1.0.0-alpha09)), then the issue disappears. 
```kotlin
val camera = cameraProvider.bindToLifecycle(lifecycleOwner, cameraSelector, preview)
previewView.preferredImplementationMode = ImplementationMode.TEXTURE_VIEW
preview.setSurfaceProvider(previewView.createSurfaceProvider(camera.cameraInfo))
````
However, taking into account this comment, seems that it is not recommended:

- https://github.com/android/camera-samples/pull/198#discussion_r406349236

### Screenshot
![device-2020-04-24-174439](https://user-images.githubusercontent.com/6617870/80231186-4ec28580-8653-11ea-8989-b8d60235af49.png)

### Device information
- **Device name**: Samsung Galaxy Note5
- **Model**: SM-N920C
- **Android version**: 7

**Comment by TheMelody** [comment]
previewView.preferredImplementationMode = ImplementationMode.TEXTURE_VIEW

Great, solved the official bug。

**Comment by mgarciaguerrero** [comment]
@owahltinez any advice on this? Is `previewView.preferredImplementationMode = ImplementationMode.TEXTURE_VIEW` the official solution to solve this issue?

**Comment by owahltinez** [comment]
Forcing `TextureView` implementation is only a temporary workaround, which I would discourage for production apps. The long-term plan is for the CameraX library to choose the appropriate implementation for all devices. I reported the issue in the library's tracker, and I'm closing it here since it's not an issue with the sample (but feel free to continue the conversation).

**Comment by mgarciaguerrero** [comment]
Thanks @owahltinez for the clarification 👍

**Comment by clhols** [comment]
@owahltinez Can you provide a link to the issue you created on the library's tracker, so we can monitor when this is fixed?
