### ISSUE TITLE
Sample CameraXBasic sometimes uses infrared camera on Pixel 4

### ISSUE THREAD

**Issue by sam5727** [android/camera-samples#217]
Hi, recently I found a issue on camera sample CameraXBasic using Google Pixel 4.
If I keep allowing and denying the camera access permission, sometimes it'll use the IR camera on Preview. 
But the reproducibility of this issue is like about 20%, and it only happens using front facing camera.
I guess that because there are two type of front facing camera on pixel 4 and don't know how to pick when the `lensFacing` is equal to `CameraSelector.LENS_FACING_FRONT`.

thanks!!

**Comment by owahltinez** [comment]
Thanks for reporting! This is a known issue and will be fixed by the library in its next release: https://android-review.googlesource.com/c/platform/frameworks/support/+/1280413/
