### ISSUE TITLE
Draw canvas on PreviewView

### ISSUE THREAD

**Issue by test690** [android/camera-samples#220]
I have a canvas object and I want to show it on the camera preview. Is there a way to do that?

I tried to use draw method on `viewFinder` but it did not work
```
val canvas = Canvas()

paint.apply {
    color = Color.RED
    textSize = 80.0f
    strokeWidth = 8.0f
}

canvas.drawLine(0f,0f,50f,50f,paint)
binding.viewFinder.draw(canvas)
```

There is a way to draw canvas on camera preview but it works only for `SurfaceView` not `PreviewView`.

```
surfaceHolder = surfaceView!!.holder
val canvas: Canvas = surfaceHolder!!.lockCanvas()

paint.apply {
    color = Color.RED
    textSize = 80.0f
    strokeWidth = 8.0f
}

canvas.drawLine(0f,0f,50f,50f,paint)
surfaceHolder!!.unlockCanvasAndPost(canvas)
```
The problem is `SurfaceView` works only with `camera2` library, and I cannot use it with `camerax`. If the solution is to use `SurfaceView`, Is there a way to do that with `camerax`?

**Comment by owahltinez** [comment]
This repo is for issues with the samples. For questions about usage, please use the `android-camerax` tag on StackOverflow or start a thread in the [developer forums](https://g.co/camerax/developers).
