### ISSUE TITLE
CameraX crashes when running in background

### ISSUE THREAD

**Issue by Michael14K** [android/camera-samples#222]
Hi, 
after running CameraXBasic on my phone the app crashes nearly always when I move the app into background (home button or "other apps" button). 
Please see attachments for further information.
My device is a Motorola G3 running on 6.0.1 and no alterations to the code where made prior.
I am fairly new in android development so my apologize for not being more specific. Hope I could help.

Kind regards,
Michael

[Camera_x.pdf](https://github.com/android/camera-samples/files/4577060/Camera_x.pdf)
[bugreport-2020-05-04-20-38-06.zip](https://github.com/android/camera-samples/files/4577061/bugreport-2020-05-04-20-38-06.zip)

**Comment by Michael14K** [comment]
I also noticed that the preview of the CameraXBasic is quite slow and lagging.

**Comment by owahltinez** [comment]
Thanks for creating this issue and sending the bug report. The team is looking into it :-)

**Comment by Sehyris** [comment]
I'm also facing the same issue. 
Do you have any updates?

**Comment by owahltinez** [comment]
This issue has been acknowledge and will be fixed in a future release of the library. A workaround is for the app to use their own executor and not shut that executor down until all images have been returned (or accounted for).

**Comment by owahltinez** [comment]
This issue should now be fixed after updating to `beta04`, please reopen if that's not the case
