### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by andresbuitront** [android/camera-samples#223]
yes i know this is java but i dont found another place to do my issue, i send email and report i implement a method to take a photo from dev android website

![image](https://user-images.githubusercontent.com/41592428/81099317-56462200-8ed0-11ea-9029-7eb5faf13669.png)

![image](https://user-images.githubusercontent.com/41592428/81099360-6a8a1f00-8ed0-11ea-9b10-8971cdea44af.png)

but when try to recover the image in the Intent data parameter, always is null (in the second picture i try two method that i found in stackoverflow but always null)

**Comment by owahltinez** [comment]
This repo is for issues related to the sample, feel free to create a question in StackOverflow and use `android-camera2` for the tag.
