### ISSUE TITLE
CameraXBasic - Preview is stretched

### ISSUE THREAD

**Issue by marko995** [android/camera-samples#224]
Hi,
I started CameraXBasic, and Preview is stretched in width. Capture work just fine.
I know this [issue16](https://github.com/android/camera-samples/issues/16) , but too much is changed.
This is screenshot:
![device-2020-05-06-184859](https://user-images.githubusercontent.com/26909234/81205144-94277100-8fca-11ea-9e2d-805e1e0bad38.png)
phone is LG g3

I had tested on another phone: xiaomi mi2 and xiaomi mi2 lite, and it's work very well.

**Comment by owahltinez** [comment]
Thanks for reporting! I think this is the same as #212 , it will likely be fixed by `beta04`
