### ISSUE TITLE
CameraXBasic sample shows a stretched preview

### ISSUE THREAD

**Issue by dthul** [android/camera-samples#227]
Not sure if this is an issue with the sample code or with the camerax library itself. The CameraXBasic sample produces a stretched live preview on one of our devices (see attached screenshot below).

Device Model: Samsung Galaxy S4 (GT-I9505)
Android Version: 5.0.1

![Screenshot_2020-04-26-21-45-11](https://user-images.githubusercontent.com/4162457/81497833-68a1d080-92c1-11ea-9294-37ea8f0e2d75.png)

**Comment by owahltinez** [comment]
Thanks for reporting this issue, it's the same as #224 and it is being fixed in the next release of the CameraX library. Closing this since it's not the sample's fault :-)
