### ISSUE TITLE
CameraX support on external cameras using USB

### ISSUE THREAD

**Issue by latinosamuel** [android/camera-samples#228]
Hello,
Can anyone tell if USB cameras are already supported by CameraX, using the latest version?
Thanks

**Comment by owahltinez** [comment]
The issue tracker is being used for problems with the unmodified samples. If you have questions about usage, please use tag `android-camerax` in StackOverflow or start a thread in the [developer forums](https://g.co/camerax/developers). CameraX currently does not support USB cameras.
