### ISSUE TITLE
How to get the final preview resolution ?

### ISSUE THREAD

**Issue by photongh** [android/camera-samples#229]
I am using cameraX(version 1.0.0-beta03) 
I create a Preview usecase like this
`preview = new Preview.Builder()
// We request aspect ratio but no resolution
           .setTargetAspectRatio(screenAspectRatio)
           // Set initial target rotation
            .setTargetRotation(rotation)
            .build();`
when displaying the camera preview with PreviewView，how can I get the final preview resolution？
the offical documents is quite outdata,

**Comment by owahltinez** [comment]
If you want the size of the view, you can just wait until it has been laid out and then do:
```kt
// Make sure it runs in the view's main thread
view.post {
    val height = view.height
    val width = view.width
}
```
