### ISSUE TITLE
Camerax  Inconsistent White Balance and Flash Result

### ISSUE THREAD

**Issue by fjr619** [android/camera-samples#232]
When i'm using cameraXBasic with flash ON, in dark condition, the image sometimes got blue white balance, but if i switch camera from back to front to back again then capture with flash ON in same lightning condition it will give me correct white balances

And sometime i got very over expose image.

#### very overexpose with flash
![Screenshot_20200511-205730](https://user-images.githubusercontent.com/9444636/81570026-3d56d880-93ca-11ea-89d9-3a3a22c01179.jpg)

#### wrong white balance
![Screenshot_20200511-205455](https://user-images.githubusercontent.com/9444636/81569617-b6096500-93c9-11ea-9441-b766e745c752.jpg)

#### correct white balance
![Screenshot_20200511-205501](https://user-images.githubusercontent.com/9444636/81569627-b9045580-93c9-11ea-8e1d-096319ddbebb.jpg)

#### *Note
All image with flash and in same dark condition
Android 10, Oneplus 6

**Comment by owahltinez** [comment]
The issue tracker is being used for problems with the unmodified samples. If you have questions about usage, please use tag `android-camerax` in StackOverflow or start a thread in the [developer forums](https://g.co/camerax/developers)
