### ISSUE TITLE
CameraXBasic wrong aspect ratio on Nexus 5

### ISSUE THREAD

**Issue by clhols** [android/camera-samples#238]
Running the CameraXBasic sample on the Nexus 5 with Android 5.0.1.

The "view finder" doesn't take up all of the screen and the aspect ratio of the camera preview is wrong.

See attached screenshot where the camera is pointed at a coin.

![device-2020-05-14-150114](https://user-images.githubusercontent.com/761265/81937798-5fcc3a00-95f4-11ea-8f7b-e6230d39c74a.png)

**Comment by owahltinez** [comment]
Thanks for reporting!

First, I find pretty amazing that you still have a working Nexus 5; mine kicked the bucket a while ago.

It looks like the same as #224 , which is being fixed in the next version of the library and is not a problem with the sample.
