### ISSUE TITLE
samples in java

### ISSUE THREAD

**Issue by rruffer** [android/camera-samples#241]
Please. I know that nowadays they are using the kotlin a lot. But java is still being used a lot. And converting a kotlin project to java is very difficult. Could you make samples in java? would help me a lot.

**Comment by owahltinez** [comment]
Unfortunately, Android is Kotlin-first; we focus on creating and maintaining samples in Kotlin. We evaluate whether a sample needs a Java version on a case-by-case basis, and if there's enough developer interest we will port this sample to Java.

**Comment by sliontc** [comment]
I'm also expecting the Java version.

**Comment by LiorA1** [comment]
old versions exists in the archive..

**Comment by topherbuckley** [comment]
How is developer interest gauged? Is there somewhere we can bump/vote/push for this?
