### ISSUE TITLE
CameraX: Image Rotation is incorrect

### ISSUE THREAD

**Issue by binhlt1310** [android/camera-samples#243]
my case is user do not enable auto rotate, have any way to get rotation of image correctly
property rotationDegrees of ImageProxy.ImageInfo in analyze method always return 90 although camera is in portrait or landscape

**Comment by owahltinez** [comment]
This repo is for issues with the samples. For questions about usage, please use the `android-camerax` tag on StackOverflow or start a thread in the [developer forums](https://g.co/camerax/developers).
