### ISSUE TITLE
setTargetAspectRatioCustom can only be called with in the same library group

### ISSUE THREAD

**Issue by mertceyhan** [android/camera-samples#244]
`setTargetAspectRatioCustom` gets one parameter as Rational, but Rational isn't a CameraX class. This causes an error on Android Studio.  `@RestrictTo(Scope.LIBRARY_GROUP)` can be removed from the function.

**Comment by owahltinez** [comment]
This repo is for issues with the samples. For questions about usage, please use the `android-camerax` tag on StackOverflow or start a thread in the [developer forums](https://g.co/camerax/developers).
