### ISSUE TITLE
CameraX Is there a way to capture timelapse video? Set Camera WhiteBalance ?

### ISSUE THREAD

**Issue by RookieExaminer** [android/camera-samples#248]
CameraWhiteBalance Is there a way to capture timelapse video?
Set Camera WhiteBalance ?

**Comment by RookieExaminer** [comment]
Exposure time and iso

**Comment by RookieExaminer** [comment]
camerax_version = '1.0.0-beta03'

**Comment by owahltinez** [comment]
The issue tracker is being used for problems with the unmodified samples. If you have questions about usage, please use tag `android-camerax` in StackOverflow or start a thread in the [developer forums](https://g.co/camerax/developers)
