### ISSUE TITLE
Preview Rotation

### ISSUE THREAD

**Issue by Winny-Wiky** [android/camera-samples#249]
Hello, i meet a bug in version beta03, when i take a photo then rotation the preview view, the show image isn't rotation and  it deformed, but it's ok in beta02, please help me.

the capture picture
![1](https://user-images.githubusercontent.com/22487173/83127281-8d44d780-a10c-11ea-8cb6-b3cd6aa50a95.png)

i click the rotation
![2](https://user-images.githubusercontent.com/22487173/83127382-ac436980-a10c-11ea-8789-313193b75097.png)

another bug, i click the home button and then return the app, the preview view become dark
![3](https://user-images.githubusercontent.com/22487173/83129165-f75e7c00-a10e-11ea-80be-572494b3f2ae.png)

**Comment by owahltinez** [comment]
The issue tracker is being used for problems with the unmodified samples. If you have questions about usage, please use tag `android-camerax` in StackOverflow or start a thread in the [developer forums](https://g.co/camerax/developers)

**Comment by Winny-Wiky** [comment]
Thank you for your reply， i confuse the problem that it's ok in beta02 and go wrong in beta03,  there is some fix in beta03 about preview view? @owahltinez
