### ISSUE TITLE
Slow Motion demo needs fpsRange.lower instead of FPS_PREVIEW_ONLY constant

### ISSUE THREAD

**Issue by cajax** [android/camera-samples#252]
Hi!
The comment in `CameraFragment` says FPS is guaranteed to be 30, but actually it is multiples of 30.

For example OnePlus 7pro provides two options - 240 and 480 FPS. The latter requires at least 60 FPS for preview.
When trying to run with current code the app fails with this error:
`java.lang.IllegalArgumentException: Fps range [30, 480] in the request is not a supported high speed fps range [[240, 240], [480, 480], [60, 480], [30, 240]]`

**Comment by owahltinez** [comment]
This sounds like an device-specific implementation error. As per [the documentation](https://developer.android.com/reference/android/hardware/camera2/params/StreamConfigurationMap#getHighSpeedVideoFpsRanges()), 30 FPS is guaranteed for preview-only use cases:
> For each fixed FPS range, there will be one corresponding variable FPS range [30, fps_max]
