### ISSUE TITLE
No supported surface combination is found for camera device - Id : 0.  May be attempting to bind too many use cases

### ISSUE THREAD

**Issue by mm46468648** [android/camera-samples#255]
when use  CameraX.bindToLifecycle(this, preview, imageCapture, videoCapture）this method,occur this exception
on my MI 5X device

**Comment by owahltinez** [comment]
The issue tracker is being used for problems with the unmodified samples. If you have questions about usage, please use tag `android-camerax` in StackOverflow or start a thread in the [developer forums](https://g.co/camerax/developers)
