### ISSUE TITLE
nexus5 is stretched when use surfaceView. but it is ok when use textureview

### ISSUE THREAD

**Issue by zhouyueyuedsf** [android/camera-samples#257]
![image](https://user-images.githubusercontent.com/9395087/84975006-f9888900-b156-11ea-9264-e7568499330a.png)

**Comment by zhouyueyuedsf** [comment]
upgrade 'androidx.camera:camera-view:1.0.0-alpha09' -> alpha12 . it will be ok

**Comment by owahltinez** [comment]
Please use the latest version of the sample, this issue should be fixed (reopen if that's not the case)
