### ISSUE TITLE
Preview view is upside down

### ISSUE THREAD

**Issue by Sotatek-ChienPhan** [android/camera-samples#258]
Preview is upside down  some device

**Comment by Sotatek-ChienPhan** [comment]
How to fix it?

**Comment by owahltinez** [comment]
Can you please provide the make and model of the specific device where this is happening? Are you modifying the sample code in any way?

**Comment by Sotatek-ChienPhan** [comment]
Hi @owahltinez , Device:  ACTI-T24T-01   android 8.1.0. Thanks

**Comment by Raja2141** [comment]
I am facing the same issue, I am taking the video on portrait mode but when I see the video it will upside down to 180 degrees how to resolve please let me
