### ISSUE TITLE
Jpeg Depth option is not coming for my Pixel4

### ISSUE THREAD

**Issue by vivekgabadiya** [android/camera-samples#260]
I was trying camera2basic application on my Pixel4 to check the depth image capturing feature but it is not displaying me an option to select depth capture. It is showing me Front JPEG(2) please check the screenshot of my device. If I continue to capture process by selecting Front JPEG(2) option then it is capturing a picture which looks like an IR image. 

What changes I have to do to make it work please suggest.

![Camera2Basic_Pixel4](https://user-images.githubusercontent.com/8841869/85393846-4ca17800-b56b-11ea-8689-067d93063cde.jpeg)

**Comment by owahltinez** [comment]
I believe Pixel 4 only supports depth output in the latest version of Android 11.
