### ISSUE TITLE
Captured video is mirrored when using front camera

### ISSUE THREAD

**Issue by ranasaha1212** [android/camera-samples#264]
I am using camera x but cannot able to get rid of this issue. When I capture video from front camera, the video gets mirrored. Is there any function in the library to turn off the mirroring of frames capturing?

**Comment by owahltinez** [comment]
The issue tracker is being used for problems with the unmodified samples. If you have questions about usage, please use tag `android-camerax` in StackOverflow or start a thread in the [developer forums](https://g.co/camerax/developers)
