### ISSUE TITLE
Google Pixel 2 XL camera problems

### ISSUE THREAD

**Issue by liungkejin** [android/camera-samples#265]
There are two problems:
Devices: Google Pixel 2 XL (9.0/10.0), System version: QQ1A.191205.008  App: Camera2Basic (Kotlin)

1. if i use TEMPLATE_PREVIEW, preview image is fine, but when i take picture by TEMPLATE_STILL_PICTURE, final picture color style is different with preview image
### Preview
<img src="https://user-images.githubusercontent.com/2999326/86564736-45ca2a80-bf99-11ea-81a7-db899a14a118.png" width="300" alt="Preview" />

### Picture
<img src="https://user-images.githubusercontent.com/2999326/86564742-48c51b00-bf99-11ea-8fe1-5a80d3f0bfaf.png" width="300" alt="Picture" />

2. if I use TEMPLATE_RECORD/TEMPLATE_VIDEO_SNAPSHOT/TEMPLATE_MANUAL, the front camera, ratio 4:3  preview image becomes darkens, but ratio 16:9 and back camera is fine!
### Preview
<img src="https://user-images.githubusercontent.com/2999326/86565154-e6b8e580-bf99-11ea-8b70-e2e18a430bfc.png" width="300" alt="Preview" />

### Picture
<img src="https://user-images.githubusercontent.com/2999326/86565160-e91b3f80-bf99-11ea-8b00-fc9e4a7984d3.png" width="300" alt="Picture" />

But system camera everything is fine!!

**Comment by owahltinez** [comment]
@liungkejin the templates can do different things for different cameras, and that's actually controlled by the device manufacturers. If you want fine control over each frame, then you should either:
- Continue to use templates but apply more configuration parameters, such as AWB, AE, etc.
- Use [the manual template](https://developer.android.com/reference/android/hardware/camera2/CameraDevice#TEMPLATE_MANUAL) and set all configuration parameters yourself
