### ISSUE TITLE
How toachieve (video recording and capture frames in real time) simultaneously? 

### ISSUE THREAD

**Issue by abhishektiwari-kiwi** [android/camera-samples#270]
I need to capture frames to perform some analysis along with video recording.
Suggest me any reliable solution.
Help me out.

**Comment by owahltinez** [comment]
The issue tracker is being used for problems with the unmodified samples. If you have questions about usage, please use tag `android-camerax` in StackOverflow or start a thread in the [developer forums](https://g.co/camerax/developers)
