### ISSUE TITLE
Orientation Issue on Pixel 2 API 26 Emulator

### ISSUE THREAD

**Issue by onurays** [android/camera-samples#274]
Images are always rotated 90 degrees as below. Do you think this is a CameraX bug or because this sample (and Glide) is not respecting the Exif Info?

Camera feed:
![Screenshot_1595425705](https://user-images.githubusercontent.com/1254401/88184316-34d91480-cc3b-11ea-99f7-9ea8b95aaf53.png)

Preview:
![Screenshot_1595425712](https://user-images.githubusercontent.com/1254401/88184322-386c9b80-cc3b-11ea-98d0-d87b755e7ac5.png)

**Comment by EdwardvanRaak** [comment]
Have you checked the rotation values in:

```
        imageCapture = ImageCapture.Builder()
            .setTargetRotation(rotation)
```

and

`imageCapture?.targetRotation = view.display.rotation` in the `displayListener`?

They should be 0 or `ROTATION_0`

**Comment by owahltinez** [comment]
I'm unable to reproduce this issue, please reopen if it persists with the latest version of the emulator and Android Studio.
