### ISSUE TITLE
Simpler Hello World style example? 

### ISSUE THREAD

**Issue by topherbuckley** [android/camera-samples#275]
I've gone through all the samples and I'm finding both the camera2Basic and cameraXBasic apps to be anything but basic. The camera2Basic CameraFragment.kt file is 480 lines long. The cameraXBasic CameraFragment.kt is 602 lines long. I appreciate all the work and thought that has gone into exemplifying all the APIs have to offer, but at the same time, I thought the whole point of cameraX was to abstract things and make it easier to set up? 

Is there no simpler Hello World style examples out there to help us get started? I mean something with no GUI components, other than a single PreviewView, no buttons, no imageCapture, just the bare bones to get a working app. I'm happy to read the docs and API reference to add on everything later, but as it stands, I'm just hacking away at this example code until something breaks. Especially for those of us developing in Java, having to read through all this Kotlin to figure out what is necessary to make a simple Java app work, is quite time consuming. CodeLabs has some example much closer to what I'm hoping for, but these are also all in Kotlin. Am I alone in this? 

The [docs](https://developer.android.com/guide/topics/media/camera#custom-camera) all seem to acknowledge they are out of date by stating things like:
>Note: The following guide is for the older, deprecated Camera API. For new or advanced camera applications, the newer android.hardware.camera2 API is recommended.

But there doesn't seem to be any walk-through on how to start a camera2 app. Am I missing this somewhere in the docs? 

Also, there are a few links at the bottom of the [docs](https://developer.android.com/guide/topics/media/camera#sample) for Java based camera2Basic apps, but these [links](https://github.com/android/camera-samples/tree/master/Camera2BasicJava/) all appear to be 404 dead.

**Comment by owahltinez** [comment]
Thanks for the feedback, for a simpler step-by-step guide to help you learn about CameraX I would recommend looking at [our codelab](https://codelabs.developers.google.com/codelabs/camerax-getting-started/) or the [training guide](g.co/camerax) (see the sections under "Documentation").
