### ISSUE TITLE
Camera2Basic - Trigger button is below navigation bar

### ISSUE THREAD

**Issue by guillaume-tgl** [android/camera-samples#283]
Following [this change](https://github.com/android/camera-samples/pull/281), the trigger button is now below the navigation bar on Samsung Galaxy S9 with Android 10:

![Screenshot_20200825-102722_Camera2Basic](https://user-images.githubusercontent.com/2244170/91151183-a20a1a80-e6bd-11ea-8cfd-56300caedab7.jpg)

**Comment by owahltinez** [comment]
Thanks for reporting this! It sounds like we should take into account the side of the navigation bar, probably a straightforward fix.
