### ISSUE TITLE
CameraX works on Android Q but not on Android R

### ISSUE THREAD

**Issue by xiaobohuo** [android/camera-samples#304]
I am adapting my app which uses cameraX to android 11;
But when I called the following function ImageCapture.takePicture(),
I received  "CameraCaptureSession: Session 0: Exception while stopping repeating";
it did not crash,but showed Black camera preview on the emulator.
Hope anyone can help.

**Comment by owahltinez** [comment]
This is a known issue, please try updating the SDK tools and the emulator to the latest version and the problem should go away.

If it doesn't, feel free to reopen.
