### ISSUE TITLE
ImageAnalysis giving lower resolution for ImageProxy

### ISSUE THREAD

**Issue by arpitcybernetyx** [android/camera-samples#310]
**Code changes :**
1. did set resolution instead of set aspect ration
2. In ImageAnalysis printed the width and height of ImageProxy to determine the resolution we get while analysis .

**Issue :**
Set resolution is 3840*2160 ( 8mp camera cross checked resolution) So, imagecapture giving full resolution but ImageAnalysis is only giving 1980 by1080
**Log print** : E/CameraXBasic: analyze(): imageProxy = 1920,1080

**CODE :**

  ```
  // ImageAnalysis
    imageAnalyzer = ImageAnalysis.Builder()
            .setTargetResolution(Size(3840, 2160))
            .build()
            .also {
                it.setAnalyzer(cameraExecutor, {
                    Log.e(TAG, "analyze(): imageProxy = ${it.width},${it.height},${it.format},${it.imageInfo}")
                    val bitmap = imageToBitmap(it)
                    Log.e(TAG, "analyze(): image = ${bitmap?.width},${bitmap?.height}")
                    bitmap?.recycle()
                    // Do image analysis here if you need bitmap
                })
            }
```

Have also raised the same on bug tracker : https://issuetracker.google.com/issues/169350823

**Comment by owahltinez** [comment]
Thanks for opening this issue! It looks like the team is already responding to your questions in the other issue tracker, which is more appropriate for library requests like this one. I'm closing this in favor of https://issuetracker.google.com/issues/169350823.
