### ISSUE TITLE
Camera2 flashmode issue

### ISSUE THREAD

**Issue by dwajot** [android/camera-samples#318]
I'm using sample of camera2 basic sample and try to a little modify if. I add 
captureRequest.set(CaptureRequest.CONTROL_AE_MODE, CaptureRequest.CONTROL_AE_MODE_ON_AUTO_FLASH)
to the captureRequest with TEMPLATE_PREVIEW and TEMPLATE_STILL_CAPTURE but nothing happened.
When I try to check flash on with FLASH_MODE_TORCH - it does work. 
Tested on Oneplus 3t with android 9.

**Comment by owahltinez** [comment]
The issue tracker is being used for problems with the unmodified samples. If you have questions about usage, please use  StackOverflow or start a thread in the [developer forums](https://g.co/camerax/developers)
