### ISSUE TITLE
rotation issue of saved image

### ISSUE THREAD

**Issue by klower** [android/camera-samples#321]
steps:
1. take photo in horizotal mode and save image
2. the image display horizontal

how to display vertical image like system camera?
![image](https://user-images.githubusercontent.com/4176873/95702163-2b7da800-0c7e-11eb-9ef6-e881e5258005.png)
I need to display like this below:
![image](https://user-images.githubusercontent.com/4176873/95702248-5e27a080-0c7e-11eb-8e12-b3c8dc670a8f.png)

**Comment by alexcohn** [comment]
Usually, the EXIF orientation flag will be written as part of the Jpeg header. The viewer can read the flag and apply the necessary rotation.

**Comment by klower** [comment]
So how can I save EXIF into the captured image?

**Comment by alexcohn** [comment]
You can use [ExifInterface](https://developer.android.com/reference/androidx/exifinterface/media/ExifInterface).

**Comment by owahltinez** [comment]
As @alexcohn indicates, it seems that the issue is on the way the image is displayed. If you use Glide / Koil, images are rotated appropriately according to the EXIF metadata.
