### ISSUE TITLE
Preview is Shrinked when fix the height of TextureView in xml

### ISSUE THREAD

**Issue by sandeepmnit** [android/camera-samples#326]
Module : Camera2Video

When I am setting the height of textureView to 320dp in xml with width match_parent , Preview video is Shrinked. Is there any way to see the top video from camera in TextureView rather than showing the complete Shrinked video.
So basically, I want to show the textureView on half of the screen starting from top and want to record the video which is visible in the half textureView. 
I don't know how can I show the half camera preview in TextureView here. Is there any way it can be achieved with your library?

**Comment by owahltinez** [comment]
The issue tracker is being used for problems with the unmodified samples. If you have questions about usage, please use  StackOverflow or start a thread in the [developer forums](https://g.co/camerax/developers)
