### ISSUE TITLE
CameraXBasic - increase FPS for image analysis

### ISSUE THREAD

**Issue by rnrvs** [android/camera-samples#328]
Hello,

I´ve tried to enhance the CameraXBasic application to analyze images at a faster rate. This is how I tried it:

        val builder = ImageAnalysis.Builder()
        val camera2InterOp = Camera2Interop.Extender(builder)
        camera2InterOp.setCaptureRequestOption(CaptureRequest.CONTROL_AE_MODE, CaptureRequest.CONTROL_AE_MODE_OFF)
        camera2InterOp.setCaptureRequestOption(CaptureRequest.CONTROL_AE_TARGET_FPS_RANGE, Range<Int>(60, 120))
        imageAnalyzer =  builder.build()
        imageAnalyzer!!.setAnalyzer(cameraExecutor, LuminosityAnalyzer { luma ->
                       // Values returned from our analyzer are passed to the attached listener
                       // We log image analysis results here - you should do something useful
                       // instead!
                       Log.d(TAG, "Average luminosity: $luma")
                      })

It is running on AVD (even if I can´t see a FPS increase, but this may be related to the virtual environment) but when I run it on a real device (S7 mobile phone) I just have a black screen. After closing the CameraXBasic app, even the real Android Camera App reports a failure and needs several restarts to work again.

Do you have any idea? Thanks in advance!

**Comment by owahltinez** [comment]
The issue tracker is being used for problems with the unmodified samples. If you have questions about usage, please use tag `android-camerax` in StackOverflow or start a thread in the [developer forums](https://g.co/camerax/developers)
