### ISSUE TITLE
Video formats listed differ from what is reported by getHighSpeedFpsRangesFor(size)

### ISSUE THREAD

**Issue by darrinps** [android/camera-samples#333]
Running the application I'm not seeing some of the sizes that are reported by getHighSpeedFpsRangesFor(size).

As one example, on a Pixel 3XL running Android 11 I see:

For size: 1280x720 Ranges are
[30, 240]
[240, 240]

For size: 640x480 Ranges are
[30, 240]
[240, 240]

For size: 1920x1080 Ranges are
[30, 120]
[120, 120]

However, only 1920x1080 at 60fps is listed in the camera-samples display. No mention of the 1920x1080 at 120 for example is displayed nor are any resolutions at 120 fps displayed. 

Here is a little utility to pull the FPS ranges for each size the camera reports back as high speed compatible. Shouldn't what it reports (the ones above) be in the list that the camera-samples app reports?

import android.app.Activity
import android.content.Context.CAMERA_SERVICE
import android.hardware.camera2.CameraAccessException
import android.hardware.camera2.CameraCharacteristics
import android.hardware.camera2.CameraManager
import android.hardware.camera2.CameraMetadata
import timber.log.Timber

class CameraUtil(private val activity: Activity) {
    private lateinit var cameraManager: CameraManager

    private fun cameraId(lens: Int): String {
        var deviceId = listOf<String>()
        try {
            val cameraIdList = cameraManager.cameraIdList
            deviceId = cameraIdList.filter { lens == cameraCharacteristics(it, CameraCharacteristics.LENS_FACING) }
        } catch (e: CameraAccessException) {
            Timber.e(e.toString())
        }
        return deviceId[0]
    }

    private fun <T> cameraCharacteristics(cameraId: String, key: CameraCharacteristics.Key<T>): T {
        val characteristics = cameraManager.getCameraCharacteristics(cameraId)
        return when (key) {
            CameraCharacteristics.LENS_FACING -> characteristics.get(key)!!
            CameraCharacteristics.SCALER_STREAM_CONFIGURATION_MAP -> characteristics.get(key)!!
            CameraCharacteristics.SENSOR_ORIENTATION -> characteristics.get(key)!!
            else -> throw  IllegalArgumentException("Key not recognized")
        }
    }

    private fun hasCompatibleCamera(): Boolean {
        val cameraId = cameraManager.cameraIdList[0]
        val characteristics = cameraManager.getCameraCharacteristics(cameraId)
        val cameraCapabilities = characteristics.get(CameraCharacteristics.REQUEST_AVAILABLE_CAPABILITIES)
        return cameraCapabilities?.contains(
            CameraMetadata.REQUEST_AVAILABLE_CAPABILITIES_BACKWARD_COMPATIBLE
        ) ?: false
    }

    fun findBackCameraCapability(): List<CameraCapabilityData> {
        val cameraDataList = mutableListOf<CameraCapabilityData>()

        cameraManager = activity.getSystemService(CAMERA_SERVICE) as CameraManager

        if (!hasCompatibleCamera()) {
            Timber.w("Back camera missing or disabled")
            ToastUtil.show(activity.applicationContext, "No back camera available. Cannot continue")
            return cameraDataList
        }

        try {
            val idList = cameraManager.cameraIdList

            val maxCameraCnt = idList.size

            for (index in 0 until maxCameraCnt) {
                val cameraId = cameraManager.cameraIdList[index];
                val characteristics = cameraManager.getCameraCharacteristics(cameraId);

                val map = characteristics.get(CameraCharacteristics.SCALER_STREAM_CONFIGURATION_MAP);

                map?.highSpeedVideoFpsRanges

                val highSpeedVideoSizes = map?.highSpeedVideoSizes

                var rangeIndex = 0

                for (size in highSpeedVideoSizes!!) {
                    val highSpeedVideoFPSRangesFor = map.getHighSpeedVideoFpsRangesFor(size)

                    Timber.d("For size: $size Ranges are")

                    for (range in highSpeedVideoFPSRangesFor) {
                        Timber.d("$range")
                        if(range.lower == range.upper) {
                            Timber.d("Will skip this one")
                        }
                        else {
                            cameraDataList.add(rangeIndex++, CameraCapabilityData(size, range))
                        }
                    }
                }
            }
        } catch (e: CameraAccessException) {
            e.printStackTrace();
        }

        return  cameraDataList
    }
}

**Comment by owahltinez** [comment]
Perhaps there is something going on with your device. My Pixel 3XL displays all the available resolutions:
![image](https://user-images.githubusercontent.com/41451293/100133123-5ef24b80-2e54-11eb-89bd-924441308e75.png)

You can see that we use the same code that you suggested [as part of the sample](https://github.com/android/camera-samples/blob/main/Camera2SlowMotion/app/src/main/java/com/example/android/camera2/slowmo/fragments/SelectorFragment.kt#L115).
