### ISSUE TITLE
how to avoid refreshing of screen while changing flash mode in android X

### ISSUE THREAD

**Issue by vick16ach** [android/camera-samples#334]
I'm trying to change the flash mode like below
```
when {
    ImageCapture.FLASH_MODE_AUTO == imageCapture!!.flashMode -> {
        imageCaptureFlashMode = ImageCapture.FLASH_MODE_ON
        idFlashControl.setImageResource(R.drawable.ic_flash_on)
        startCamera()
    }
...
...
```
in startCamera() I'm binding the use cases like below
```
cameraProvider?.unbindAll()
val cameraX = cameraProvider?.bindToLifecycle(
            this, cameraSelector, preview, imageCapture
        )
```

unbinding is recreating the surface. So, when I change the flash mode the screen goes black and come back to life like a new activity is created. 

How to avoid this ?

**Comment by owahltinez** [comment]
The issue tracker is being used for problems with the unmodified samples. If you have questions about usage, please use tag `android-camerax` in StackOverflow or start a thread in the [developer forums](https://g.co/camerax/developers)
