### ISSUE TITLE
CameraXBasic: on legacy Samsung: Saves images to root directory and gallery never updates

### ISSUE THREAD

**Issue by dkati** [android/camera-samples#335]
Good evening. As title says:

CameraXBasic example saves the image to
**/data/data/com.dialog.myapplication/files/2020-11-21-12-39-56-595.jpg**
and photo never shows up at gallery.

Samsung S4, android lollipop (5.0.1 sdk 21)

Update:
I am trying to find a way to handle camera captures on both new devices and that stupid samsung touchwiz thing.
Those guys touched the "stock" intent and its pretty useless with no documentation provided

Update2:
On camera2basic, camera preview is rotated and stressed and image is not shown at gallery too ( i dont know if it is saved though)

CameraX seems really nice and promising. i hope it will be stabilized on those wannabe-coreHacked touchwiz devices

**Comment by owahltinez** [comment]
Hi @dkati, the images show in the default gallery application on the devices I have tested. The images themselves are not rotated, they use EXIF metadata and then the photo viewer must rotate the image. Again, the gallery application is responsible for that.

I would suggest trying a different gallery application, please reopen if the issue persists.

**Comment by dkati** [comment]
The "saves to root directory" is unrelated to gallery though

**Comment by owahltinez** [comment]
The choice of output directory is deliberate: https://github.com/android/camera-samples/blob/main/CameraXBasic/app/src/main/java/com/android/example/cameraxbasic/MainActivity.kt#L70
