### ISSUE TITLE
Camera2Video crashed

### ISSUE THREAD

**Issue by andreyvatoropinit** [android/camera-samples#367]
Hello!
i downloaded camera-sampes.
i added project to android studio. Project camera2video
BUILD SUCCESSFUL
I started on pixel emulate phone. and when i pressed button rec app crashed
same behavior on real phone Samsung s20. Android 10

**Comment by remmel** [comment]
You have to hold the button : https://github.com/android/camera-samples/issues/332#issuecomment-725714194
