### ISSUE TITLE
Using ImageAnalysis is extremely slow on low-spec Nokia 5.1

### ISSUE THREAD

**Issue by bilsou** [android/camera-samples#41]
The `CameraXBasic` sample runs really slow on Nokia 5.1 because of the `imageAnalyzer` when binding the usecase in `CameraX.bindToLifecycle(viewLifecycleOwner, preview, imageAnalyzer)`. If one removes the `imageAnalyzer` parameter, the frame rate gets normal again. 

Are you doing any copy before calling the base function `fun analyze(image: ImageProxy, rotationDegrees: Int) {` ?

**Comment by jxdom** [comment]
Me too,my device is meizhu5.1

**Comment by owahltinez** [comment]
@bilsou there is no image copy as far as I'm aware. How are you configuring the image analysis use case? Are you using the [ACQUIRE_LATEST_IMAGE](https://developer.android.com/reference/androidx/camera/core/ImageAnalysis.ImageReaderMode.html#ACQUIRE_LATEST_IMAGE) mode?

**Comment by owahltinez** [comment]
Closing for now, please reopen if you are still experiencing this issue when using ACQUIRE_LATEST_IMAGE mode

**Comment by mohammad-ali-dehlvi** [comment]
I am facing the same issue with ACQUIRE_LATEST_IMAGE mode

**Comment by adeeb1201** [comment]
I am also facing the issue in Emulator, Pixel 5 API 29. Will this happen in realtime too?
