### ISSUE TITLE
Camera2Basic app sample crashes on Android 12 (S) when taking a photo - ERROR_CAMERA_DEVICE (4 error)

### ISSUE THREAD

**Issue by anonym24** [android/camera-samples#432]
Camera2Basic app sample crashes on Android 12 (S) when taking a photo, only preview works fine

https://github.com/android/camera-samples/blob/main/Camera2Basic/app/src/main/java/com/example/android/camera2/basic/fragments/CameraFragment.kt#L286

```
 java.lang.RuntimeException: Camera 0 error: (4) Fatal (device)
        at com.example.android.camera2.basic.fragments.CameraFragment$openCamera$2$1.onError(CameraFragment.kt:276)
```

```
E/CameraCaptureSession: Session 0: Exception while stopping repeating: 
    android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error
```

**Comment by akumakhalibagas** [comment]
how to fix this issue? pleasee

**Comment by chinnuu05** [comment]
Still running into this issue 2 years later... Seriously, this has not been fixed yet?
