### ISSUE TITLE
How to use third camera 

### ISSUE THREAD

**Issue by Reginer** [android/camera-samples#440]
I know use front and back camera，but how to use third camera ？？？

`Camera.open(2)`

**Comment by ggfan** [comment]
CameraX focus on the use cases: with the give use case, will select the most appropriate camera among available cameras (to use as the default front and back ones).  If you have needs for that specific camera, we like to know your usage scenarios. may you file an issue [here](https://issuetracker.google.com/issues/new?component=618491&template=1257717)? thanks!

**Comment by Reginer** [comment]
Understood, I thought CameraX could be achieved.

**Comment by Reginer** [comment]
https://issuetracker.google.com/issues/205741598

**Comment by ggfan** [comment]
thank you, update the bug, we can follow it up there.
