### ISSUE TITLE
CameraX have increase preview Surface.

### ISSUE THREAD

**Issue by Office-Murtaza** [android/camera-samples#448]
When i show the camera like duet mode it will not fixed their position. It also overlay on videoView .i am using the camera aspect ratio is RATIO_16_9. this bug create in most device and when i have made changing in aspect ratio with RATIO_4_3 its will also increase. Please
guide me how to fixed CameraX preview.

**Comment by ggfan** [comment]
can elaborate more on your "duet mode"?
