### ISSUE TITLE
Merge conflicts

### ISSUE THREAD

**Issue by syslogic** [android/camera-samples#505]
It appears to me as my authorship had been infringed upon, which I find highly unprofessional.

> Whenever a non-Googler wants to submit a patch to a Google open source project, they must first sign a Contributor License Agreement (CLA). **This allows the contributor to retain their ownership in the code submitted** while granting Google the necessary legal rights to use that contribution

https://github.com/android/camera-samples/pull/489

It is pretty obvious that the PR could have been directly merged, because the requested changes were just non-sense only to complain about something - and they not have been applied by the actor, as well. 

 - Got anything to say about this ridiculous practice?
 - How do I permanently opt-out of the CLA agreement?

**Comment by donovanfm** [comment]
Hi, syslogic. Are you saying that you are seeing changes you authored on the android:main branch?

I can't see your changes anymore in that PR, except for the one diff I commented on. If you look at [that line](https://github.com/android/camera-samples/blob/main/Camera2Basic/app/build.gradle#L34) in our main branch, you'll see that it's still the original line without your change.

**Comment by syslogic** [comment]
The code of the PR had been copied in pristine form ...this is what version control says.
Now I just want to cancel this CLA, because I don't agree to such unserious methods ...
but there isn't a delete button: https://cla.developers.google.com/clas

I'm also planning to migrate most to AWS or Huawei Cloud because of this.

**Comment by donovanfm** [comment]
It sounds like you discovered this was a problem with version control and some merge conflicts. I'm going to close this issue since there's no problem with the repo itself.

**Comment by syslogic** [comment]
@donovanfm The problem is that you didn't merge the PR and therefore caused that mess on my side.
