### ISSUE TITLE
CameraXBasic build warnings

### ISSUE THREAD

**Issue by v-hogood** [android/camera-samples#512]
camera-samples/CameraXBasic/app/src/main/java/com/android/example/cameraxbasic/MainActivity.kt: (86, 36): 'getter for externalMediaDirs: Array<(out) File!>!' is deprecated. Deprecated in Java
camera-samples/CameraXBasic/app/src/main/java/com/android/example/cameraxbasic/fragments/CameraFragment.kt: (465, 61): 'toUpperCase(Locale): String' is deprecated. Use uppercase() instead.
camera-samples/CameraXBasic/app/src/main/java/com/android/example/cameraxbasic/fragments/CameraFragment.kt: (513, 61): 'Camera' is deprecated. Deprecated in Java
camera-samples/CameraXBasic/app/src/main/java/com/android/example/cameraxbasic/fragments/CameraFragment.kt: (513, 68): 'ACTION_NEW_PICTURE: String' is deprecated. Deprecated in Java
camera-samples/CameraXBasic/app/src/main/java/com/android/example/cameraxbasic/fragments/GalleryFragment.kt: (34, 30): 'FragmentStatePagerAdapter' is deprecated. Deprecated in Java
camera-samples/CameraXBasic/app/src/main/java/com/android/example/cameraxbasic/fragments/GalleryFragment.kt: (58, 58): 'FragmentStatePagerAdapter' is deprecated. Deprecated in Java
camera-samples/CameraXBasic/app/src/main/java/com/android/example/cameraxbasic/fragments/GalleryFragment.kt: (68, 9): 'setter for retainInstance: Boolean' is deprecated. Deprecated in Java
camera-samples/CameraXBasic/app/src/main/java/com/android/example/cameraxbasic/fragments/GalleryFragment.kt: (76, 57): 'toUpperCase(Locale): String' is deprecated. Use uppercase() instead.
camera-samples/CameraXBasic/app/src/main/java/com/android/example/cameraxbasic/fragments/GalleryFragment.kt: (149, 61): 'yes: Int' is deprecated. Deprecated in Java
camera-samples/CameraXBasic/app/src/main/java/com/android/example/cameraxbasic/fragments/GalleryFragment.kt: (169, 61): 'no: Int' is deprecated. Deprecated in Java
camera-samples/CameraXBasic/app/src/main/java/com/android/example/cameraxbasic/fragments/PermissionsFragment.kt: (44, 13): 'requestPermissions(Array<(out) String!>, Int): Unit' is deprecated. Deprecated in Java
camera-samples/CameraXBasic/app/src/main/java/com/android/example/cameraxbasic/fragments/PermissionsFragment.kt: (53, 15): 'onRequestPermissionsResult(Int, Array<(out) String!>, IntArray): Unit' is deprecated. Deprecated in Java
camera-samples/CameraXBasic/app/src/main/java/com/android/example/cameraxbasic/utils/ViewExtensions.kt: (29, 14): 'SYSTEM_UI_FLAG_LOW_PROFILE: Int' is deprecated. Deprecated in Java
camera-samples/CameraXBasic/app/src/main/java/com/android/example/cameraxbasic/utils/ViewExtensions.kt: (30, 22): 'SYSTEM_UI_FLAG_FULLSCREEN: Int' is deprecated. Deprecated in Java
camera-samples/CameraXBasic/app/src/main/java/com/android/example/cameraxbasic/utils/ViewExtensions.kt: (31, 22): 'SYSTEM_UI_FLAG_LAYOUT_STABLE: Int' is deprecated. Deprecated in Java
camera-samples/CameraXBasic/app/src/main/java/com/android/example/cameraxbasic/utils/ViewExtensions.kt: (32, 22): 'SYSTEM_UI_FLAG_IMMERSIVE_STICKY: Int' is deprecated. Deprecated in Java
camera-samples/CameraXBasic/app/src/main/java/com/android/example/cameraxbasic/utils/ViewExtensions.kt: (33, 22): 'SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION: Int' is deprecated. Deprecated in Java
camera-samples/CameraXBasic/app/src/main/java/com/android/example/cameraxbasic/utils/ViewExtensions.kt: (34, 22): 'SYSTEM_UI_FLAG_HIDE_NAVIGATION: Int' is deprecated. Deprecated in Java
camera-samples/CameraXBasic/app/src/main/java/com/android/example/cameraxbasic/utils/ViewExtensions.kt: (83, 24): 'setter for systemUiVisibility: Int' is deprecated. Deprecated in Java

**Comment by donovanfm** [comment]
Thanks for pointing these out! A recent pull request has addressed these warnings.
