### ISSUE TITLE
 Failed to create capture session; configuration failed

### ISSUE THREAD

**Issue by sonalpatel22** [android/camera-samples#54]
CaptureSession: CameraCaptureSession.onConfiguredFailed()
Camera: CameraDevice.onError(): 0 with error: ERROR_CAMERA_IN_USE
error occures when back from gallery view

**Comment by owahltinez** [comment]
@sonalpatel22 can you please give us more details about the specific device you are using and the exact reproduction steps? Does this happen 100% of the time using the latest version of the sample and the library?

**Comment by owahltinez** [comment]
We just upgraded the sample to `alpha05`. Feel free to reopen if this issue is still reproducible with the latest version of the sample.
