### ISSUE TITLE
alpha04 has broken Samsung Galaxy S8 preview

### ISSUE THREAD

**Issue by Horovtom** [android/camera-samples#56]
It looks like it chooses some incredibly small resolution or sth as well as distorting the image. In any case the  preview is unusable.

Here is a screenshot:
![Screenshot_20190822-122424_CameraX Basic](https://user-images.githubusercontent.com/20874093/63507450-0fe29b80-c4d8-11e9-886c-85f4991c9acc.jpg)

**Comment by PhungVanHoa** [comment]
Try to change the aspect ratio and surface size

**Comment by rahulraj64** [comment]
The same issue here. The preview is blur in alpha04 version. Its look fine in alpha01

**Comment by owahltinez** [comment]
This is an issue with the library that is being investigated and will (hopefully) be fixed in the next monthly release: https://issuetracker.google.com/issues/140194349

**Comment by owahltinez** [comment]
We have just updated the sample to alpha-05. Please reopen if this issue has not been resolved!
