### ISSUE TITLE
Knowing actual selected resolution before analyze is called for the first time?

### ISSUE THREAD

**Issue by sonicdebris** [android/camera-samples#59]
I am using the `ImageAnalysis` use case, and I need to initialize my analysis code with the image resolution (width and height).

Is there any way to get the resolution picked during camera initialization any time before the first call to `ImageAnalysis.Analyzer.analyze(...)` ?

**Comment by owahltinez** [comment]
Good question. We checked with the product team working on CameraX and this is not currently possible today, but we are looking into potentially new APIs to enable developers to do this.

**Comment by owahltinez** [comment]
Closing for now. Feel free to reach out to the team at https://g.co/camerax/developers if you want to start a discussion about this over there!
