### ISSUE TITLE
CameraX chooses low resolution for given aspect ratio

### ISSUE THREAD

**Issue by Dem0n13** [android/camera-samples#60]
I want to get the best quality for square aspect ratio and setup the next preview and capture configs for CameraX.

```
val SQUARE_ASPECT_RATIO = Rational(1, 1)

val previewConfig = PreviewConfig.Builder().apply {
    setTargetAspectRatio(SQUARE_ASPECT_RATIO)
    setTargetRotation(viewFinder.display.rotation)
}.build()
preview = Preview(previewConfig)

val imageCaptureConfig = ImageCaptureConfig.Builder().apply {
    setCaptureMode(ImageCapture.CaptureMode.MAX_QUALITY)
    setTargetAspectRatio(SQUARE_ASPECT_RATIO)
    setTargetRotation(viewFinder.display.rotation)
}.build()
imageCapture = ImageCapture(imageCaptureConfig)

CameraX.bindToLifecycle(this, preview, imageCapture)
```

CameraX chooses 352x288px resolution, so result image resolution equals 288x288px. From documentation it should be the highest resolution available for current device, but it is not.

Tested on emulator and Google Pixel 3.

**Comment by owahltinez** [comment]
What resolutions are available in the devices you are testing this in? Asking for a squared aspect ratio will severely limit the resolutions that CameraX will attempt to choose from.

**Comment by Giammaofwar** [comment]
Got the same problem, if I specify the aspect ratio CameraX will choose an incredible low resolution. Tried with more ratio on really good camera (Galaxy s10+)

**Comment by owahltinez** [comment]
Please try again with the updated version of the sample since we just upgraded to `alpha05`. This problem should have been resolved now, feel free to reopen if that's not the case.
