### ISSUE TITLE
CameraManager.getCameraIdList() is empty on my tablet.

### ISSUE THREAD

**Issue by MobileDevStar** [android/camera-samples#65]
CameraManager.getCameraIdList() is empty on my tablet.

Device specs:
Lenovo TB-X304F, android 8.1.0, 2.0 GB ram, Qualcomm Snapdragon 425, display 1280x800

Please let me know ASAP if you know how to fix
Thank you

**Comment by owahltinez** [comment]
It sounds like an issue with your device. Is it a certified device? I.e. did it come with Google apps like the Play Store installed?
