### ISSUE TITLE
Camera Preview is Pixeleted

### ISSUE THREAD

**Issue by aqsashahid123** [android/camera-samples#77]
In some devices like nokia 1.6 and samsung galaxy A10 the preview resolution is very low.
However it is working fine in all other devices.
The resolution is very very low.
Whereas the pixels of captured image are proper and according to the device's maximam resolution.

**Comment by owahltinez** [comment]
This sounds like https://issuetracker.google.com/issues/140194349 which has now been fixed but likely won't be included in the library until `alpha06`

**Comment by waliahimanshu** [comment]
Tested on Samsung device and this is fixed in `alpha06`. The api has changed  and sample app still used `alpha05`.

**Comment by owahltinez** [comment]
Thanks for testing that @waliahimanshu! We are working on updating the sample, and it will use `alpha06` soon.

**Comment by owahltinez** [comment]
We have a PR under review which will fix this issue: #97

**Comment by owahltinez** [comment]
The sample has been updated to `alpha06`, please reopen if this is still an issue

**Comment by askarsyzdykov** [comment]
Hi @owahltinez! I have similar issue with `alpha06` and `alpha08`

This is preinstalled Android 9 app
![photo_2020-01-20 12 00 45](https://user-images.githubusercontent.com/3222305/72702365-a1843100-3b7c-11ea-840b-f4e24006afee.jpeg)

This is sample:
![photo_2020-01-20 12 00 44](https://user-images.githubusercontent.com/3222305/72702411-d1333900-3b7c-11ea-99e2-3650828cd5a1.jpeg)

As you can see, the quality on the second picture a bit pixelated.
