### ISSUE TITLE
CameraX memory leak

### ISSUE THREAD

**Issue by TooLazyy** [android/camera-samples#94]
Download CameraX sample. 
Add new empty activity.
Add LeakCanary dependency and
`LeakSentry.refWatcher.watch(this)` to `onDestroyView` of `CameraFragment`.
 After app started and all permissions granted start new activity and call finish on `MainActivity`.
Like this f.x.
```
        Handler().postDelayed({
            startActivity(Intent(this, TestActivity::class.java))
            finish()
        }, 10000L)
```
You will see CameraX instance is leaking.
Some screens from my app. In your sample leaks are the same.
<img src="https://user-images.githubusercontent.com/18148514/67793511-08b5ac00-fa8c-11e9-9546-ac9e8ca4edb2.jpg" width="200" height="300">
<img src="https://user-images.githubusercontent.com/18148514/67793774-88437b00-fa8c-11e9-94a8-dd037a570ab1.jpg" width="200" height="300">
<img src="https://user-images.githubusercontent.com/18148514/67793828-a0b39580-fa8c-11e9-9516-d6d8698dd149.jpg" width="200" height="300">

**Comment by owahltinez** [comment]
Thanks for reporting this @TooLazyy, I think these memory leaks are happening at the library layer and not the sample so there's not much we can't do to fix it here :(

Can you open a bug in the [AOSP issue tracker](https://issuetracker.google.com/issues?q=componentid:618491) for the camera library?

**Comment by owahltinez** [comment]
Closing since this is a library issue that should be tracked in the corresponding issue tracker.

**Comment by ocarey** [comment]
Also having issues with CameraX memory leak w/ version alpha06 and alpha09. I was using alpha06+TextureView and upgraded to alpha09+PreviewView today to try and fix the memory leak. Unfortunately, there's still a memory leak related to PreviewView and its underlying TextureView. This is seemingly the exact same leak I had with alpha06 + TextureView. This occurs in my own app & the CameraXBasic example app.

Also adding this to issue: https://issuetracker.google.com/141188637

LeakCanary CameraXBasic:
![CameraXBasic Memory Leak](https://user-images.githubusercontent.com/37121709/73915589-8a2d8f00-4870-11ea-88f3-78fdc8d028c9.jpg)

**Comment by ocarey** [comment]
By adding this to Activity onDestroy() I was able to force a Garbage Collection of my Camera Activity. Version alpha09 w/ CameraXBasic example app:

```
override fun onDestroy() {
        super.onDestroy()
        tearDownCamera()
    }
```

```
private fun tearDownCamera() {
        val cameraProviderFuture = ProcessCameraProvider.getInstance(this)
        cameraProviderFuture.addListener(Runnable {
            val cameraProvider: ProcessCameraProvider = cameraProviderFuture.get()
            cameraProvider.shutdown()
        }, ContextCompat.getMainExecutor(this))
    }
```

Best,
Owen

**Comment by Colanderr** [comment]
I am facing the same issue, but @ocarey 's workaround sometimes crashes the app. 
I've also noticed that for every instance of the activity that's leaked, there is also a leaked androidx.lifecycle.ReportFragment, so I'm guessing that it's a bug in the camera lifecycler library (androidx.camera:camera-lifecycle)

**Comment by Sottti** [comment]
@ocarey apparently `shutdown` is `@RestrictTo(Scope.TESTS)`
