### ISSUE TITLE
IllegalArgumentException: Suggested resolution map missing resolution for camera 1

### ISSUE THREAD

**Issue by Tarikmnk** [android/camera-samples#98]
hi,

I want start front camera but app crashed.
my code : setLensFacing(lCameraX.LensFacing.FRONT)

error I received :
IllegalArgumentException: Suggested resolution map missing resolution for camera 1 
camera version : alpha06

**Comment by owahltinez** [comment]
@Tarikmnk this repo is for issues with the sample, not with CameraX. Since you are modifying the sample, I suggest that you ask your question in StackOverflow or the forums at [g.co/camerax/developers](g.co/camerax/developers)
